apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n8zo3axzq-nodejs 
  janus-idp.io/tekton: n8zo3axzq-nodejs
  backstage.io/kubernetes-id: n8zo3axzq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n8zo3axzq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml